<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7BIh6e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7BIh6e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU7BIh6e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU7BIh6e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU7BIh6e\App_KernelDevDebugContainer([
    'container.build_hash' => 'U7BIh6e',
    'container.build_id' => 'b0b8c7ab',
    'container.build_time' => 1612996174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7BIh6e');
