<?php

namespace ContainerU7BIh6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CqANenbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cqANenb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cqANenb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ItemController::getodolistItems' => ['privates', '.service_locator.KE4MXTB', 'get_ServiceLocator_KE4MXTBService', true],
            'App\\Controller\\ItemController::postItemeTodolist' => ['privates', '.service_locator.GN_EThU', 'get_ServiceLocator_GNEThUService', true],
            'App\\Controller\\ToDoListController::patchTodolist' => ['privates', '.service_locator.KiPnV2S', 'get_ServiceLocator_KiPnV2SService', true],
            'App\\Controller\\ToDoListController::postTodolist' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\UserController::GetUsers' => ['privates', '.service_locator..z9lMtz', 'get_ServiceLocator__Z9lMtzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ItemController:getodolistItems' => ['privates', '.service_locator.KE4MXTB', 'get_ServiceLocator_KE4MXTBService', true],
            'App\\Controller\\ItemController:postItemeTodolist' => ['privates', '.service_locator.GN_EThU', 'get_ServiceLocator_GNEThUService', true],
            'App\\Controller\\ToDoListController:patchTodolist' => ['privates', '.service_locator.KiPnV2S', 'get_ServiceLocator_KiPnV2SService', true],
            'App\\Controller\\ToDoListController:postTodolist' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\UserController:GetUsers' => ['privates', '.service_locator..z9lMtz', 'get_ServiceLocator__Z9lMtzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ItemController::getodolistItems' => '?',
            'App\\Controller\\ItemController::postItemeTodolist' => '?',
            'App\\Controller\\ToDoListController::patchTodolist' => '?',
            'App\\Controller\\ToDoListController::postTodolist' => '?',
            'App\\Controller\\UserController::GetUsers' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ItemController:getodolistItems' => '?',
            'App\\Controller\\ItemController:postItemeTodolist' => '?',
            'App\\Controller\\ToDoListController:patchTodolist' => '?',
            'App\\Controller\\ToDoListController:postTodolist' => '?',
            'App\\Controller\\UserController:GetUsers' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
