<?php

namespace ContainerU7BIh6e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KE4MXTBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KE4MXTB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KE4MXTB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itemRepository' => ['privates', 'App\\Repository\\ItemRepository', 'getItemRepositoryService', true],
            'temService' => ['privates', 'App\\Service\\ItemService', 'getItemServiceService', true],
            'toDoListServiceRepository' => ['privates', 'App\\Repository\\ToDoListServiceRepository', 'getToDoListServiceRepositoryService', true],
        ], [
            'itemRepository' => 'App\\Repository\\ItemRepository',
            'temService' => 'App\\Service\\ItemService',
            'toDoListServiceRepository' => 'App\\Repository\\ToDoListServiceRepository',
        ]);
    }
}
