<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnrpBuh\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnrpBuh/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUnrpBuh.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUnrpBuh\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerUnrpBuh\App_KernelTestDebugContainer([
    'container.build_hash' => 'UnrpBuh',
    'container.build_id' => 'c6397e9e',
    'container.build_time' => 1612996340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnrpBuh');
