<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_item_postitemetodolist' => [['id'], ['_controller' => 'App\\Controller\\ItemController::postItemeTodolist'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/items/todolist']], [], []],
    'app_item_getodolistitems' => [[], ['_controller' => 'App\\Controller\\ItemController::getodolistItems'], [], [['text', '/items/todolist']], [], []],
    'app_todolist_posttodolist' => [[], ['_controller' => 'App\\Controller\\ToDoListController::postTodolist'], [], [['text', '/todolist']], [], []],
    'app_todolist_patchtodolist' => [['id'], ['_controller' => 'App\\Controller\\ToDoListController::patchTodolist'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/todolist']], [], []],
    'app_user_getusers' => [[], ['_controller' => 'App\\Controller\\UserController::GetUsers'], [], [['text', '/users']], [], []],
];
