<?php

namespace ContainerUahn4R3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ItemService' shared autowired service.
     *
     * @return \App\Service\ItemService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ItemService.php';

        return $container->privates['App\\Service\\ItemService'] = new \App\Service\ItemService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
